sudo: required
dist: bionic

language: cpp

compiler:
  - gcc

cache:
  directories:
    - $HOME/travis_cache

jobs:
  include:
    - stage: build_deps_and_cache
      script: >
        ./mcrouter/scripts/install_ubuntu_18.04.sh "$(pwd)"/mcrouter-install deps
        && tar -zcvf $HOME/travis_cache/install_deps_ubuntu_18.04.tar.gz -C "$(pwd)"/mcrouter-install/install .
    - stage: mcrouter
      script: >
        mkdir -p "$(pwd)"/mcrouter-install/install
        && tar -xzvf $HOME/travis_cache/install_deps_ubuntu_18.04.tar.gz -C "$(pwd)"/mcrouter-install/install
        && ./mcrouter/scripts/install_ubuntu_18.04.sh "$(pwd)"/mcrouter-install mcrouter

notifications:
  email:
    - mcrouter@fb.com
